@baseUrl = http://localhost:3000/forum
@token = put your token here
@userId = cmarhm4g90000dcgciw2yr4rr
@questionId = cmawwui9k0001dcq6kdq014vh
@answerId = cmawwui9k0001dcq6kdq014vh

GET {{baseUrl}}/user

###

POST {{baseUrl}}/user
Content-Type: application/json

{
  "name": "John Doe",
  "password": "Pw12345!",
  "email": "jd3000@example.com"
}

###

GET {{baseUrl}}/user/{{userId}}


###

PATCH {{baseUrl}}/user/{{userId}}
Content-Type: application/json
Authorization: Bearer {{token}}


{
  "name": "John Doe Updated"
}

###
DELETE {{baseUrl}}/user/{{userId}}
Content-Type: application/json
Authorization: Bearer {{token}}


###

POST {{baseUrl}}/auth/login
Content-Type: application/json

{
 
  "password": "123456",
  "email": "johndoe2@example.com"
}


###
GET {{baseUrl}}/user
Content-Type: application/json
Authorization: Bearer {{token}}


###
POST {{baseUrl}}/questions
Content-Type: application/json
Authorization: Bearer {{token}}

{
 
  "title": "What's JWT?",
  "description": "I'm building a api"
}


###

GET http://localhost:3000/forum/questions/
Content-Type: application/json
Authorization: Bearer {{token}}



###

GET {{baseUrl}}/questions/
Content-Type: application/json
Authorization: Bearer {{token}}


###
GET  {{baseUrl}}/questions
Content-Type: application/json
Authorization: Bearer {{token}}


###
POST {{baseUrl}}/answers/{{answerId}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
 
  "description": "i do not know"
}
